version: "3"
name: template
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: app_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.local
    command: rails s -b '0.0.0.0'
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
      - next:/app/.next
    ports:
      - "8000:3000"
volumes:
  postgres_data:
  node_modules:
  next:

